CREATE TABLE `bird_encyclopedia` (
	`id` int AUTO_INCREMENT NOT NULL,
	`speciesNameZh` varchar(128) NOT NULL,
	`speciesNameEn` varchar(128) NOT NULL,
	`scientificName` varchar(128) NOT NULL,
	`taxonomy` varchar(128),
	`representativePicUrl` text,
	`summary` text,
	`morphology` text,
	`behavior` text,
	`diet` text,
	`distribution` text,
	`habitat` text,
	`breeding` text,
	`vocalizations` text,
	`conservationStatus` varchar(64),
	`funFacts` text,
	`campusObservationTips` text,
	`sightingCount` int NOT NULL DEFAULT 0,
	`lastSeenAt` bigint,
	`generatedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `bird_encyclopedia_id` PRIMARY KEY(`id`),
	CONSTRAINT `bird_encyclopedia_speciesNameZh_unique` UNIQUE(`speciesNameZh`)
);
